name: Combined Workflow

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-todo:latest

  deploy:
    needs: docker-build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: |
          export $(grep -v '^#' .env.pub/.env.dev | xargs)
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Pulumi
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Deploy
        run: |
          cd .pulumi
          pip install -r requirements.txt
          pulumi login --local
          pulumi stack select dev || pulumi stack init dev
          pulumi up --yes
          pulumi stack output instance_id > instance_id.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_PASSPHRASE }}
      - name: Upload instance_id
        uses: actions/upload-artifact@v2
        with:
          name: instance_id
          path: .pulumi/instance_id.txt
